version: '2.4'

volumes:
  public:
    driver: local

services:
  web: 
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    environment: 
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password